### ISSUE TITLE
Additional Dark Mode and Light Mode customization

### ISSUE THREAD

**Issue by Polignao** [Til0r/open-profiler#1]
## Expected Behavior
Possibility to customize color palette of the portfolio, both dark mode and light mode, in a simple way inside open-profiler.config.json. 

## Actual Behavior
Can only modify the main color, used on header, footer and images, inside open-profiler.config.json

**Comment by Til0r** [comment]
@Polignao thanks for opening this issue! Your proposal is fantastic, I'll review and provide feedback as soon as possible. Appreciate your input!
